// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: tb.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ToggleButtonClient is the client API for ToggleButton service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToggleButtonClient interface {
	// Sends a heartbeat.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type toggleButtonClient struct {
	cc grpc.ClientConnInterface
}

func NewToggleButtonClient(cc grpc.ClientConnInterface) ToggleButtonClient {
	return &toggleButtonClient{cc}
}

func (c *toggleButtonClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/protos.ToggleButton/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToggleButtonServer is the server API for ToggleButton service.
// All implementations must embed UnimplementedToggleButtonServer
// for forward compatibility
type ToggleButtonServer interface {
	// Sends a heartbeat.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedToggleButtonServer()
}

// UnimplementedToggleButtonServer must be embedded to have forward compatible implementations.
type UnimplementedToggleButtonServer struct {
}

func (UnimplementedToggleButtonServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedToggleButtonServer) mustEmbedUnimplementedToggleButtonServer() {}

// UnsafeToggleButtonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToggleButtonServer will
// result in compilation errors.
type UnsafeToggleButtonServer interface {
	mustEmbedUnimplementedToggleButtonServer()
}

func RegisterToggleButtonServer(s grpc.ServiceRegistrar, srv ToggleButtonServer) {
	s.RegisterService(&ToggleButton_ServiceDesc, srv)
}

func _ToggleButton_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToggleButtonServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ToggleButton/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToggleButtonServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToggleButton_ServiceDesc is the grpc.ServiceDesc for ToggleButton service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToggleButton_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ToggleButton",
	HandlerType: (*ToggleButtonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _ToggleButton_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tb.proto",
}
