name: Generate Package

on:
  release:
    types: [created]

  workflow_dispatch:
jobs:
  generate-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set env
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set env to production
        if: "!contains(github.event.release.name, '-')"
        run: |
          echo "deployment=production" >> $GITHUB_ENV
      - name: Set env to staging
        if: contains(github.event.release.name, '-')
        run: |
          echo "deployment=staging" >> $GITHUB_ENV

      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: GitHub registry login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build-and-push
        if: "!contains(github.event.release.name, '-')"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}

      - name: Build-and-push
        if: "contains(github.event.release.name, '-')"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
